name: flareline_uikit
description: "flareline_uikit"
version: 0.0.8
homepage:

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get_storage: ^2.1.1

  provider: ^6.1.2

  syncfusion_flutter_charts: ^31.2.3

  syncfusion_flutter_datagrid: ^31.2.3

  flutter_svg: ^2.0.9

  file_picker: ^10.3.3

  flutter_dropzone: ^4.0.2

  responsive_builder: ^0.7.0

  avatar_glow: ^3.0.1

  uuid: ^4.3.3

  logger: ^2.0.2+1

  rx_event_bus: ^2.0.1

  json_annotation: ^4.8.1

  window_location_href: ^2.0.0

  desktop_drop: ^0.5.0

  flutter_bloc: ^9.1.0

  equatable: ^2.0.5

  stream_transform: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
